development:
  site_name: WPI Dwyer & Associates
  domain: http://wpi.local
  image_magick_path: /usr/local/bin
test:
  domain: http://wpi.local

production:
  site_name: WPI Dwyer & Associates
  domain: http://agents.wpi-properties.com
  image_magick_path: /usr/local/bin